"""add cause presentational and manual stats fields

Revision ID: 4890929a2919
Revises: 6dc68473d4a4
Create Date: 2026-08-26 23:33:37.311106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4890929a2919'
down_revision = '6dc68473d4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('causes', schema=None) as batch_op:
        # tag / location / story / need are NOT re-added here — they were
        # already applied to the live DB by the first (failed) run of this
        # migration before it aborted on raised_amount. Only the two
        # columns that never got added remain below.
        batch_op.add_column(sa.Column('raised_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('donors_count', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_accepted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('consent_version', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('consent_version')
        batch_op.drop_column('consent_accepted_at')

    with op.batch_alter_table('causes', schema=None) as batch_op:
        batch_op.drop_column('donors_count')
        batch_op.drop_column('raised_amount')
        # NOTE: this downgrade no longer drops tag/location/story/need
        # since this migration no longer adds them. If you need a full
        # rollback of those four too, drop them manually.

    # ### end Alembic commands ###