"""added qrcode totp

Revision ID: bf8873da1fc5
Revises: ccba6322de04
Create Date: 2026-09-08 12:03:57.636477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8873da1fc5'
down_revision = 'ccba6322de04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column(
            'totp_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        ))

    # Drop the server_default once existing rows are backfilled, so the
    # column matches the model (no default declared at the DB level).
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.alter_column('totp_enabled', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###