"""add payment_link to causes

Revision ID: ccba6322de04
Revises: ef6f97eba48e
Create Date: 2026-09-05 18:37:01.221321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccba6322de04'
down_revision = 'ef6f97eba48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('causes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_link', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('causes', schema=None) as batch_op:
        batch_op.drop_column('payment_link')

    # ### end Alembic commands ###
