"""add otp fields to admin_users

Revision ID: e33cac1be437
Revises: c9ab5281860a
Create Date: 2026-08-28 12:19:18.775261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33cac1be437'
down_revision = 'c9ab5281860a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # Made idempotent: SQLite auto-commits each ADD COLUMN individually
    # (non-transactional DDL), so a migration that fails partway through
    # leaves earlier columns in place even though Alembic never records
    # the revision as applied. Checking what's already there first makes
    # this safe to re-run no matter how far a previous attempt got.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = {col['name'] for col in inspector.get_columns('admin_users')}

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        if 'otp_code_hash' not in existing_columns:
            batch_op.add_column(sa.Column('otp_code_hash', sa.String(length=128), nullable=True))
        if 'otp_expires_at' not in existing_columns:
            batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
        if 'otp_attempts' not in existing_columns:
            # NOT NULL columns need a server_default so SQLite (and
            # Postgres) can backfill existing rows.
            batch_op.add_column(sa.Column('otp_attempts', sa.Integer(), nullable=False, server_default='0'))
        if 'otp_last_sent_at' not in existing_columns:
            batch_op.add_column(sa.Column('otp_last_sent_at', sa.DateTime(timezone=True), nullable=True))
        if 'otp_verified_until' not in existing_columns:
            batch_op.add_column(sa.Column('otp_verified_until', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = {col['name'] for col in inspector.get_columns('admin_users')}

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        if 'otp_verified_until' in existing_columns:
            batch_op.drop_column('otp_verified_until')
        if 'otp_last_sent_at' in existing_columns:
            batch_op.drop_column('otp_last_sent_at')
        if 'otp_attempts' in existing_columns:
            batch_op.drop_column('otp_attempts')
        if 'otp_expires_at' in existing_columns:
            batch_op.drop_column('otp_expires_at')
        if 'otp_code_hash' in existing_columns:
            batch_op.drop_column('otp_code_hash')

    # ### end Alembic commands ###